[network]
host = "bertrand.local"
web_port = 17352
swap_wifi = false
topology = ""

[paths]
root = "/home/tom/code"

[networks.internal.wired.x18]
name = "x18"
ip_address = "10.43.0.18"
subnet = "10.43.0.0/24"

[networks.internal.wifi.private]
name = "showbox"
ip_address = "10.43.0.1"
dhcp_start = "10.43.0.50"
dhcp_end = "10.43.0.200"

[networks.external.wifi.external]
name = "Livebox-F13E"

[usb]
x18_device_name = "X18"

[twitch]
enabled = false
account = "loopopenloop"
stream_title = "openLoop, broadcasting live from Rouen"
category = "Music"
tags = ["Live Music", "Music", "Performance"]
chat_messages = ["Stream starting soon.", "Thanks for listening."]
stream_marker_descriptions = [
  "show start",
  "song start",
  "song end",
  "set break",
  "show end",
]
id = "1523431675"
oauth_token_scopes = [
  "channel:manage:broadcast",
  "chat:edit",
  "chat:read",
  "clips:edit",
  "moderation:read",
  "moderator:manage:announcements",
]
client_id = "qyqv064pencm797xuhee5biy0yxahh"
redirect_uri = "http://localhost:17563/callback"
scopes = "channel:manage:broadcast chat:edit chat:read moderator:manage:announcements clips:edit moderation:read"
config_dir = "$HOME/.config/twitcho"
state = "SaqhIYFnE124j25yv7OJm8FQ9yLIceEh"

[lyte]
enabled = false
daemon_config = "patches/wearable-daemon.toml"

[git.reccy]
url = "git@github.com:rec/reccy.git"

[git.recs]
url = "git@github.com:rec/recs.git"

[git.twitcho]
url = "git@github.com:rec/twitcho.git"

[git.lyte]
url = "git@github.com:rec/lyte.git"

[git.showco]
url = "git@github.com:rec/showco.git"
