showco_pi_access_point_ssid = "showbox"
is_x18_wired = true
swap_wifi = false
network_topology = ""
twitcho_enabled = false
private_wifi_ssid = "showbox"
external_wifi_ssid = ""
showco_pi_host = "recs-stage.local"
showco_pi_ssh_port = "22"
showco_pi_wifi_ip_address = "10.42.0.1"
showco_pi_wifi_dhcp_start = "10.42.0.50"
showco_pi_wifi_dhcp_end = "10.42.0.200"
showco_pi_x18_ethernet_subnet = "10.43.0.0/24"
showco_x18_wired_ethernet_ip_address = "10.43.0.18"
showco_port = "17352"
twitch_account = "loopopenloop"
twitch_default_stream_title = "openLoop, broadcasting live from Rouen"
twitch_default_category = "Music"
twitch_default_tags = "[\"Live Music\",\"Music\",\"Performance\"]"
twitch_standard_chat_messages = "[\"Stream starting soon.\",\"Thanks for listening.\"]"
twitch_standard_stream_marker_descriptions = "[\"show start\",\"song start\",\"song end\",\"set break\",\"show end\"]"
twitch_id = "1523431675"
twitch_oauth_token_scopes = "[\"channel:manage:broadcast\",\"chat:edit\",\"chat:read\",\"clips:edit\",\"moderation:read\",\"moderator:manage:announcements\"]"
twitch_client_id = "qyqv064pencm797xuhee5biy0yxahh"
twitch_redirect_uri = "http://localhost:17563/callback"
twitch_scopes = "channel:manage:broadcast chat:edit chat:read moderator:manage:announcements clips:edit moderation:read"
twitch_config_dir = "$HOME/.config/twitcho"
twitch_state = "SaqhIYFnE124j25yv7OJm8FQ9yLIceEh"
x18_usb_device_name = "X18/XR18"
recs_repo = "git@github.com:rec/recs.git"
twitcho_repo = "git@github.com:rec/twitcho.git"
showco_repo = "git@github.com:rec/showco.git"
