[project]
name = "showco"
version = "0.1.0"
description = "🎪 Local show control for recs and twitcho 🎪"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.13.4",
    "reccy",
    "recs",
    "tqdm>=4.70.0",
    "typing-extensions>=4.10.0",
    "tyro>=1.0.15",
]

[tool.uv]
exclude-newer = "1 week"

[tool.uv.sources]
reccy = { git = "https://github.com/rec/reccy.git", rev = "446a2c4a6f0437463e4a3e6eaa39b4b5597ec106" }
recs = { git = "ssh://git@github.com/rec/recs.git", rev = "d572e68359a275794abf5add54c80289cf564c3b" }

[project.scripts]
showco = "showco.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pyupgrade>=3.21.2",
    "ruff>=0.16.4",
    "ty>=0.0.73",
]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["B", "E", "F", "I"]
