version: 2
ethernets:
  eth0:
    dhcp4: false
    addresses:
      - @ETH_ADDRESS@
    optional: true
wifis:
  wlan0:
    optional: true
    dhcp4: true
    access-points:
      "@WIFI_SSID@":
        password: "@WIFI_PASSWORD@"
