SHOWCO_PI_ACCESS_POINT_SSID = "showbox"
swap_wifi = false
network_topology = ""
twitcho_enabled = false
private_wifi_ssid = "showbox"
external_wifi_ssid = ""
SHOWCO_PI_HOST = "recs-stage.local"
SHOWCO_PI_USER = "show"
SHOWCO_PI_SSH_PORT = "22"
SHOWCO_PI_WIFI_IP_ADDRESS = "10.42.0.1"
SHOWCO_PI_WIFI_DHCP_START = "10.42.0.50"
SHOWCO_PI_WIFI_DHCP_END = "10.42.0.200"
SHOWCO_PI_X18_ETHERNET_SUBNET = "10.43.0.0/24"
SHOWCO_X18_WIRED_ETHERNET_IP_ADDRESS = "10.43.0.18"
SHOWCO_PORT = "17352"
TWITCH_ACCOUNT = "loopopenloop"
TWITCH_DEFAULT_STREAM_TITLE = "openLoop, broadcasting live from Rouen"
TWITCH_DEFAULT_CATEGORY = "Music"
TWITCH_DEFAULT_TAGS = "[\"Live Music\",\"Music\",\"Performance\"]"
TWITCH_STANDARD_CHAT_MESSAGES = "[\"Stream starting soon.\",\"Thanks for listening.\"]"
TWITCH_STANDARD_STREAM_MARKER_DESCRIPTIONS = "[\"show start\",\"song start\",\"song end\",\"set break\",\"show end\"]"
TWITCH_ID = "1523431675"
TWITCH_OAUTH_TOKEN_SCOPES = "[\"channel:manage:broadcast\",\"chat:edit\",\"chat:read\",\"clips:edit\",\"moderation:read\",\"moderator:manage:announcements\"]"
TWITCH_CLIENT_ID = "qyqv064pencm797xuhee5biy0yxahh"
TWITCH_REDIRECT_URI = "http://localhost:17563/callback"
TWITCH_SCOPES = "channel:manage:broadcast chat:edit chat:read moderator:manage:announcements clips:edit moderation:read"
TWITCH_CONFIG_DIR = "$HOME/.config/twitcho"
TWITCH_STATE = "SaqhIYFnE124j25yv7OJm8FQ9yLIceEh"
AUDIO_X18_USB_DEVICE_NAME = "X18/XR18"
RECS_REPO = "git@github.com:rec/recs.git"
TWITCHO_REPO = "git@github.com:rec/twitcho.git"
SHOWCO_REPO = "git@github.com:rec/showco.git"
